weights: ./model/best_model.pt
load_poly: True
train_gate_from_scratch: False

#### Reduce the frame size to 256 ####
frame_reduce: True

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xview/val_data.npy
  label_path: ./data/NTU-RGB-D/xview/val_label.pkl


#### Reduce the frame size to 256 ####
frame_reduce: True




# model
model: net.st_gcn.Model_replace
model_args:
  ##### use 3 layers model as backbone
  backbone: Model_3layers_2
  in_channels: 3
  num_class: 60
  # dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  replace_poly: True  #### For the student model, we want to replace it with poly function
  #### Enable node with polynomial
  node_wise: True
  clip_poly: True
  ##### Conduct the polynomial reduction or not
  poly_reduce: True
  lambda_penalty: 1
  ##### Keep original ReLU operation in the process
  freeze_gate: True
  # keep_relu: True


# test 
phase: test
device: 0
test_batch_size: 256

mix_precision: True
format: fp16
